### ISSUE TITLE
Enable openID token based authentication

### ISSUE THREAD

**Issue by SachinVarghese** [arrikto/oidc-authservice#24]
Currently, the oidc-authservice only enables session-based authentication used mainly for web apps. It would be great to also have openID token-based auth enabled for services behind the gateway. This would allow other many CLI applications to login to the same IDP and get a token to make requests to the cluster (basically like how kubctl works). Such token-based access would be very similar to authentication with IAP. As I see, there could be two approaches to this.
- Allow and verify ID tokens from multiple clients as per configuration. In this case, maybe the token issuer remains the same, but there could be a list of valid audiences to verify and allow requests.
- Use dex's [cross-client-trust-and-authorized-party](https://github.com/dexidp/dex/blob/master/Documentation/custom-scopes-claims-clients.md#cross-client-trust-and-authorized-party) to let other clients generate tokens on behalf of oidc-authservice app and authservice should verify these tokens accordingly.

It would be great to hear more about this.

**Comment by SachinVarghese** [comment]
KFServing [example of running a prediction](https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex#run-a-prediction) has also become rather convoluted due to the lack of such a feature. As you notice, users have resorted to copying cookies from the browser for CLI applications as well.

**Comment by yanniszark** [comment]
Hi @SachinVarghese! Right now, the authservice only supports the OIDC Authorization Code flow, which involves user interaction.
It then relies on keeping sessions in order to track the user's status.
For programmatic access, we should indeed support some kind of token-based authentication which doesn't require user interaction.

Since OIDC is already setup, we could add support for authenticating IDTokens in headers. The workload would get the IDToken through a programmatic OIDC flow (Client Credentials flow).
We are planning for something similar, but more tightly integrated with Kubernetes, which would solve the KFServing (and other) related issues.

**Comment by yhwang** [comment]
@yanniszark I am implementing an id token authenticator which gets id token from header and performs token verification (`IDTokenVerifier.Verify()`). Since id token is used, the authenticator can only check if the USERID_CLAIM is inside the token or not. If yes, it adds the value of USERID_CLAIM to the USERID_HEADER. Since IDTokenVerifier verifies the id token thoroughly, the authenticator directly relies the result and return the userinfo.
Not sure if my implementation aligns to what you plan to do.

**Comment by yanniszark** [comment]
@yhwang @SachinVarghese do your OIDC providers support such a use-case?
The OIDC Provider must have a way to issue a JWT with the AuthService's client as audience.
AFAIK, there is no standard flow to do this:
- Google uses the `urn:ietf:params:oauth:grant-type:jwt-bearer` flow with a `target_audience` parameter.
- Microsoft uses JWTs for its access tokens, so they can be used for this purpose.

**Comment by yhwang** [comment]
yes, there is no standard flow for that now. But for the sake of argument, if a user can get id-token, it would be a nice feature that oidc-authservice can use it for authentication. And as you listed above, some OIDC providers do allow you to issue id-token in some ways. This also simplified the programmatic use case with limited access of browsers.

do you have any security concern about enable such feature?

**Comment by yanniszark** [comment]
@yhwang thanks for answer! No, adding this seems logical to me, seeing that Kubernetes is also using a similar method.
Thanks for the PR, I hope to get to it soon! :)

**Comment by yhwang** [comment]
@yanniszark when will you publish a new image containing this PR? Do you have any schedule about that? Just want to know the timeline. Thanks.

**Comment by yanniszark** [comment]
@yhwang yes, I pushed an image to `gcr.io/arrikto/oidc-authservice:087a340`.
Right now we don't have automation to do that, that's why it slipped.
The main concern is security, since AFAIK there is no way to create a GCP ServiceAccount with permissions to write to a single image prefix. You can only give permissions for the whole registry.
Closing the issue since it was resolved.

**Comment by SachinVarghese** [comment]
Nice one @yhwang @yanniszark. It would be great to know if this change will be included in the next Kubeflow release?

**Comment by yhwang** [comment]
@yanniszark one question about the image: `gcr.io/arrikto/oidc-authservice:087a340`
I can't pull the image. Can you double check? Thanks

**Comment by athamark** [comment]
Hello @yhwang , sorry for the delayed response. Regarding this:
> * Would you prefer to use `gcr.io/arrikto/kubeflow/oidc-authservice` or `gcr.io/arrikto/oidc-authservice` ?
Currently, you only published new images to `gcr.io/arrikto/oidc-authservice`

We have started pushing our AuthService images to the `gcr.io/arrikto/oidc-authservice` registry instead of the `gcr.io/arrikto/kubeflow/oidc-authservice`. We have standardized on this decision. All the upcoming official AuthService images will be served there. Here is a link to the new registry: https://console.cloud.google.com/gcr/images/arrikto/GLOBAL/oidc-authservice
